namespace COTS.GameServer {

    /// <summary>
    /// <Auto-Generated>
    /// This is here so CodeMade doesn't reorganize this document
    /// </Auto-Generated>
    /// </summary>
    public enum ItemGroup {
        None,       //ITEM_GROUP_NONE,

        Ground,     //ITEM_GROUP_GROUND,
        Container,  //ITEM_GROUP_CONTAINER,
        Weapon,     //ITEM_GROUP_WEAPON, //deprecated
        Ammunition, //ITEM_GROUP_AMMUNITION, //deprecated
        Armor,      //ITEM_GROUP_ARMOR, //deprecated
        Charges,    //ITEM_GROUP_CHARGES,
        Teleport,   //ITEM_GROUP_TELEPORT, //deprecated
        MagicField, //ITEM_GROUP_MAGICFIELD, //deprecated
        Writeable,  //ITEM_GROUP_WRITEABLE, //deprecated
        Key,        //ITEM_GROUP_KEY, //deprecated
        Splash,     //ITEM_GROUP_SPLASH,
        Fluid,      //ITEM_GROUP_FLUID,
        Door,       //ITEM_GROUP_DOOR, //deprecated
        Deprecated, //ITEM_GROUP_DEPRECATED,

        Last,       //ITEM_GROUP_LAST
    }
}