using System;

namespace COTS.GameServer.World
{
    /// <summary>
    /// <Auto-Generated>
    /// This is here so CodeMade doesn't reorganize this document
    /// </Auto-Generated>
    /// </summary>
    public enum OTBMTileFlag : UInt32 {
        ProtectionZone =    0b0001, // OTBM_TILEFLAG_PROTECTIONZONE
        NoPvpZone =         0b0010, // OTBM_TILEFLAG_NOPVPZONE
        NoLogout =          0b0100, // OTBM_TILEFLAG_NOLOGOUT
        PvpZone =           0b1000  // OTBM_TILEFLAG_PVPZONE
    }
}
